import base64 as b64
"""
    THESE ARE SUPPOSED TO BE SECRET. WE NEED TO FIND THEM USING CRYPTANALYSIS!
"""
INTEGRITY_LEN = 1
FLAG = 'CTF{Ez_T4g_Cr4ftyng}'
SERVER_PUBLIC_BANNER = b64.b64decode('AXN1p+X5') 